server:
  port: 8888

spring:
  application:
    name: yyconfig-demo

# 应用配置项
yy:
  a: a00
  b: b00
  c: c00

logging:
  level:
    root: info
    cn.kimmking: debug

# 配置中心参数
yyconfig:
  server: http://localhost:9129
  app: app1
  env: dev
  ns: public
