server:
  port: 9129

spring:
  application:
    name: yyconfig-server
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:h2db
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yyconfig?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db.sql
      mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true

# 项目日志配置
logging:
  level:
    root: info

# mybatis 日志打印配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
